# https://docs.docker.com/compose/compose-file/05-services/
services:      
  # https://github.com/cao7113/hello-phx/pkgs/container/hello-api-elixir
  api:
    # image: ghcr.io/cao7113/hello-api-elixir
    build: .
    # environment:
    #   MIX_ENV: "prod"
    # https://docs.docker.com/compose/compose-file/05-services/#healthcheck
    healthcheck:
      test: bin/hello_api pid || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s

  # http://hello-api-elixir-api-1.orb.local/

  curl:
    image: curlimages/curl:8.8.0
    depends_on:
      - api
    command: >
      sh -c "
        sleep 2
        echo ping api
        curl http://api/ping
        echo
        echo ping api at port 4000
        curl http://api:4000/ping
        echo
        ping -c 3 api
        ping -q api
      "

  tool:
    image: busybox
    depends_on:
      - api
    command: >
      sh -c "
        sleep 2
        echo ping api
        wget -qO- http://api/ping
        echo
        echo ping api at port 4000
        wget -qO- http://api:4000/ping
        echo
        ping -c 3 api
        ping -q api
      "