# fly.toml app configuration file generated for hello-api-elixir on 2025-07-12T15:40:51+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hello-api-elixir'
primary_region = 'nrt'

[build]

[env]
RELEASE_DISTRIBUTION = 'name'
# use 6PN private ipv6 address
RELEASE_NODE = 'hi@hello-api-elixir.internal'
# SHOULD set with fly config
RELEASE_COOKIE = 'hello'
# use ipv6
ERL_AFLAGS = '-proto_dist inet6_tcp'
PORT = '8080'

[http_service]
internal_port = 8080
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
# size = 'shared-cpu-1x'
# iex require 512m+
memory = "512mb"
cpu_kind = 'shared'
cpus = 1
