# https://taskfile.dev
version: "3"
includes:
  fly-io:
    taskfile: ./Taskfile-fly-io.yml
    aliases: [f, fly]
    optional: true
tasks:
  default: mix test --no-start

  sh: iex -S mix run --no-start
  run: iex -S mix run
  # iex -S mix run --no-halt --detached

  up: mix bump patch && git push origin main --tag

  prel: MIX_ENV=prod mix release --overwrite
  prel-tar: MIX_ENV=prod RELEASE_TAR=1 mix release --overwrite
  prun: _build/prod/rel/hello_api/bin/hello_api start_iex
  redo-deps:
    cmds:
      - |
        mix deps.unlock --all && mix deps.clean --all && mix deps.get

  get-info: curl -v http://localhost:4000 | jq
  get-user: curl -s http://localhost:4000/users/123

  ## Docker images
  dk-builder: docker pull hexpm/elixir:1.17.1-erlang-27.0-debian-bullseye-20240612-slim
  dk-runner: docker pull debian:bullseye-20240612-slim

  ## Git ops
  cmt: mix git_ops.release
  app-info: mix git_ops.project_info
  init-release: mix git_ops.release --initial

  # Init setup
  mk-hello: mix new hello-api-elixir --app hello_api --sup
