# https://taskfile.dev
version: "3"
tasks:
  default: mix test

  sh: iex -S mix
  run: iex -S mix run
  # elixir -S mix run --no-halt --detached
  rel: MIX_ENV=prod mix release --overwrite
  prun: _build/prod/rel/hello_api/bin/hello_api start

  create: mix new hello-api-elixir --app hello_api

  untar-run:
    cmds:
      - |
        mkdir xxx
        tar -C xxx -xzf hello_api-0.1.0.tar.gz
        cd xxx
        bin/hello_api start
