name: Deploy release

on:
  push:
    branches:
      - ssh

permissions:
  contents: read

jobs:
  deploy:
    name: Deoloy to remote server by ssh
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      # https://github.com/appleboy/ssh-action
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_PRIVKEY }}
          port: 22
          script: |
            pwd
            if [ ! -d hello ]; then 
              wget https://github.com/cao7113/hello-api-elixir/releases/download/v0.1.2/hello_api-0.1.0.tar.gz
              mkdir hello
              tar -C hello -xzf hello_api-0.1.0.tar.gz
            else 
              echo existed hello
              hello/bin/hello_api stop || true
            fi
            hello/bin/hello_api daemon_iex
            hello/bin/hello_api pid
