name: Fly Deploy
on:
  push:
    tags:
      - "v*"
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # https://github.com/superfly/flyctl-actions
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy app
        run: flyctl deploy --remote-only --build-arg GIT_COMMIT_ID=$(git log -1 --format="%H") --build-arg GIT_COMMIT_TIME=$(git log -1 --format="%ct")
        env:
          # https://github.com/superfly/flyctl-actions?tab=readme-ov-file#secrets
          # https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/#speed-run-your-way-to-continuous-deployment
          # gen cmd: fly tokens create deploy -x 999999h
          # set in Github Settings -> Secrets -> Actions -> Repository secrets
          # https://github.com/cao7113/hello-api-elixir/settings/secrets/actions
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
