name: Elixir Release

on:
  push:
    tags:
      - "v*"
    branches:
      - release

permissions:
  contents: read

jobs:
  release:
    strategy:
      matrix:
        # erlef/setup-beam only supports Ubuntu and Windows at this time
        os: [ubuntu-22.04]
        otp: [25.x]
        elixir: [1.14.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: strict
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get --only prod
      - name: Make release
        run: |
          MIX_ENV=prod mix release
