name: Elixir Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    strategy:
      matrix:
        # erlef/setup-beam only supports Ubuntu and Windows at this time
        os: [ubuntu-22.04]
        otp: [25.x]
        elixir: [1.14.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: strict
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get --only prod
      - name: Make mix release
        run: |
          export COMMIT_ID=${{ github.sha }}
          export REPO_URL=${{ github.repositoryUrl }}
          export BUILD_TIME="$(date -Iseconds)"
          MIX_ENV=prod mix release
      - name: Make Github release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: _build/prod/*.tar.gz

  deploy:
    name: Deoloy to remote server by ssh
    runs-on: ubuntu-22.04
    needs: release
    steps:
      # https://github.com/appleboy/ssh-action
      # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_PRIVKEY }}
          port: 22
          script: |
            vsn=${{ github.ref_name }}
            git_repo=${{ github.repository }}

            app_root=~/hello
            script_path=${app_root}/deploy.sh

            mkdir -p $app_root  
            script_url="https://raw.githubusercontent.com/${git_repo}/main/run/deploy.sh"
            if [ ! -e $script_path ]; then
              wget -q -O $script_path $script_url
              chmod +x $script_path
              echo "Setup deploy-script into ${script_path} from ${script_url}"
            else 
              echo "Use existed deploy-script: ${script_path}, manually delete it when need update"
            fi

            $script_path $vsn $app_root bin/hello_api ${git_repo} 3
